### ISSUE TITLE
Error: specified module not found

### ISSUE THREAD

**Issue by vahagnsargsian** [wilix-team/iohook#195]
It works by running electron . always. After building with electron builder for windows, it works on all windows versions, but on some PC-s with windows 10 it gives this error.

## Expected Behavior
Run without giving errors.

## Current Behavior
Gives an error: Uncaught exception: Error: Specified module could not be found

## Steps to Reproduce (for bugs)
1.Build with electron builder for windows
2.Run installation file on windows 10

## Context
Problem is detected not on all windows 10 machines.

## Your Environment
Problem is there not matter what node, npm, electron builder version you are using.
For electron I use latest version, but error was there also with previous versions.

<a href="https://imgur.com/j0eZlze"><img src="https://i.imgur.com/j0eZlze.png" title="source: imgur.com" /></a>

**Comment by wendongwoxin** [comment]
previous versions can't work ，are there other methods can solve this problem by previous version?

**Comment by zxc23** [comment]
I get this problem as well. When installed, the iohook files are automatically unpacked and placed in that folder. I'm wondering if it's anti-virus related. Either way, I'm removing iohook from my dependencies because I can't afford users to experience this problem and I can't find more information about this to fix it.

**Comment by zxc23** [comment]
I wonder if this is all related to this fix: https://github.com/electron/electron/pull/20342

I'm going to update Electron (I was using 5) and I'll try to test on a PC that was having this problem.

**Comment by Djiit** [comment]
Hi @zxc23 , could you try with version 0.6.2 which supports Electron 7 ?

**Comment by zxc23** [comment]
I've already updated to 0.6.2 and Electron 7 but the tricky bit is that none of the PCs I have access to ever experience this issue. There are only two clients that I know have this problem but I haven't been able to get feedback on a new version yet. When I find out more, I'll post an update here.

**Comment by Djiit** [comment]
Ok thanks for your feedback. I'll close this one but please feel free to reopen a new one with your clients information as soon as you get the problem back.

**Comment by EmptyCrown** [comment]
Hey guys, was there a resolution to this?

My team and I are in the exact same situation and it seems super weird. Thing work for the vast majority of users, including for everyone on our team, but for a couple of users, the "module cannot be found" even though we have confirmed that the `iohook.node` indeed exists on their machine in the correct location. 

In our case, we need to use Electron 6.1.9, and are using iohook 0.6.5. 

To make things even weirder, iohook was working fine for a particular user I was talking to before we pushed a minor update. In the minor update, we are still importing iohook in the same way. The only noticeable difference I saw is that we are importing it from a different file and the `require` statement for `iohook` is before that of `electron` rather than after. Could this possibly matter?

**Comment by zxc23** [comment]
Using Electron 7.1.4, haven't heard report of this problem for a long while. Hoping it's gone but don't know for sure.

**Comment by EmptyCrown** [comment]
Ok great to know, thank you. Unfortunately, we need to use Electron 6 since our core technology relies on a bunch of packages that are only compatible with Electron 6. Will keep looking for a solution.

**Comment by zxc23** [comment]
Still experiencing this on the combination of Electron 7 and iohook 0.6.2

**Comment by zxc23** [comment]
An update: I've had multiple confirmations that this problem was resolved by installing Microsoft Visual C++ Redistributable on the machines via https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads.

These issues are all related:

#167
#193
#195
#224 
#245
