### ISSUE TITLE
electron-v76-darwin-x64/build/Release/iohook.node not found

### ISSUE THREAD

**Issue by quanweibai** [wilix-team/iohook#252]
i use electron 10.1.1 and i got this message 'builds/electron-v82-darwin-x64/build/Release/iohook.node not found',  how can i fix this ? i don't want to downgrade my electron version...

**Comment by a-keramat** [comment]
You could check for available versions list here
https://github.com/wilix-team/iohook/releases > your version of iohook > assets 
I don't see a compiled asset released for electron v82 for now

**Comment by quanweibai** [comment]
> You could check for available versions list here
> https://github.com/wilix-team/iohook/releases > your version of iohook > assets
> I don't see a compiled asset released for electron v82 for now

ok, thanks,
I downgrade my electron version to 9.3.1 and node version is 12.18.3
and my package.json config is:

 _"iohook": {
    "targets": [
      "electron-80"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  },
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "9.3.1"
  }_

but I still got this error message:
    **Uncaught Error: Cannot find module '/Users/dev/builds/electron-v80-darwin-x64/build/Release/iohook.node'**

any idea to fix this?

**Comment by marcelblum** [comment]
I believe the latest version of Electron supported by latest iohook 0.6.6 is Electron 8.5.2 ("electron-76").

**Comment by quanweibai** [comment]
> I believe the latest version of Electron supported by latest iohook 0.6.6 is Electron 8.5.2 ("electron-76").

downgrade to electron 8.5.2. still got this error:
    **Uncaught Error: Cannot find module '/Users/dev//builds/electron-v76-darwin-x64/build/Release/iohook.node'**
could anyone save my life （>﹏<）?

**Comment by a-keramat** [comment]
according to the documents you should set appropriate version of ABI of your node & electron in package.json :
so here is the way, you could determine what is your ABI version 

**Node** :

1. first check the node version, anywhere in your electron project: 
`console.log(process.versions.node)`
2. then visit [node release list ](https://nodejs.org/en/download/releases/) and check for your **NODE_MODULE_VERSION**

**Electron**:
1. check electron module version:
`console.log(process.versions.modules)`

Another way is to add the built files manually (which is not a good idea though): 
this way you should download the assets and extract theme in package build directory : **node_modules\iohook\builds**
the name convention is a little different, example :
`iohook-v0.6.6-node-v72-win32-x64.tar.gz >> node-v72-win32-x64`

But, I'm afraid I steel I do sth wrong. because I got another error.
if you done the solution. pls let me know if it helps

**Comment by quanweibai** [comment]
> according to the documents you should set appropriate version of ABI of your node & electron in package.json :
> so here is the way, you could determine what is your ABI version
> 
> **Node** :
> 
> 1. first check the node version, anywhere in your electron project:
>    `console.log(process.versions.node)`
> 2. then visit [node release list ](https://nodejs.org/en/download/releases/) and check for your **NODE_MODULE_VERSION**
> 
> **Electron**:
> 
> 1. check electron module version:
>    `console.log(process.versions.modules)`
> 
> Another way is to add the built files manually (which is not a good idea though):
> this way you should download the assets and extract theme in package build directory : **node_modules\iohook\builds**
> the name convention is a little different, example :
> `iohook-v0.6.6-node-v72-win32-x64.tar.gz >> node-v72-win32-x64`
> 
> But, I'm afraid I steel do sth wrong. because I got another error.
> if you done the solution. pls let me know if it helps

not try the second way yet. but I am sure the versions of node & electron I used is right.
node version 12.18.3 -> abi verison 72
electron version 7.3.3 -> abi version 75
and the package.json config is:

  _"iohook": {
    "targets": [
      "node-72",
      "electron-75"
    ],
    "platforms": [
      "win32",
      "darwin",
      "linux"
    ],
    "arches": [
      "x64",
      "ia32"
    ]
  }_

tried many version combination, still got the same error  as above mentioned...
something wrong?

**Comment by a-keramat** [comment]
the error itself says you need electron v76 files.

in my case. I got similar error (electron v80), which matches my ABI version
I updated the package.json and ran `npm install`, still got the same error. and no changes made to `iohook\build `dir.
So I added the assets manually
-----------
Have you tried to build assets manually ? 👇
https://wilix-team.github.io/iohook/manual-build.html

**Comment by quanweibai** [comment]
> the error itself says you need electron v76 files.
> 
> in my case. I got similar error (electron v80), which matches my ABI version
> I updated the package.json and ran `npm install`, still got the same error. and no changes made to `iohook\build `dir.
> So I added the assets manually
> 
> ===============
> Have you tried to build assets manually ? 👇
> https://wilix-team.github.io/iohook/manual-build.html

**"the error itself says you need electron v76 files."**
----
no. after I changed to 
node version 12.18.3 -> abi verison 72
electron version 7.3.3 -> abi version 75
I got 'Cannot find module builds/electron-v75-darwin-x64/build/Release/iohook.node'

I am trying to build assets manually . did you success?

**Comment by marcelblum** [comment]
No need to compile the module manually, you can just download the needed binary from here:
https://github.com/wilix-team/iohook/releases
And extract the .node file manually into the needed folder.
But for me whenever I've run into this problem doing a simple npm uninstall and reinstall of iohook did the trick, as long as I have my package.json configured properly. You'd see console output during the iohook install indicating that the install process is automatically downloading and extracting the needed binaries.

**Comment by a-keramat** [comment]
downgrading your electron step by step 😂
> no. after I changed to
> node version 12.18.3 -> abi verison 72
> electron version 7.3.3 -> abi version 75
> I got 'Cannot find module builds/electron-v75-darwin-x64/build/Release/iohook.node'
> 
> I am trying to build assets manually . did you success?

I haven't tried it yet. not for now

Since I needed to 
1.prevent default key action
2.control over apps which I wanted to intercept keys on theme
Currently I changed my approach, & did what I wanted using "AutoHotKey" and std Streaming played keys to node 

thanks to @marcelblum reinstalling the package solved the error `electron-v??-win32-x64/build/Release/iohook.node not found` since assets not downloading after changing version numbers in `package.json`

**Comment by quanweibai** [comment]
> compile

have tried reinstall many times, not resolved this problem.
my confuse is: the error msg said : 'Uncaught Error: Cannot find module '/Users/dev/Desktop/code/xxx/out/builds/electron-v75-darwin-x64/build/Release/iohook.node'  but there is no 'builds/' directory in '/Users/dev/Desktop/code/xxx/out/' after I installed iohook...

**Comment by quanweibai** [comment]
> No need to compile the module manually, you can just download the needed binary from here:
> https://github.com/wilix-team/iohook/releases
> And extract the .node file manually into the needed folder.
> But for me whenever I've run into this problem doing a simple npm uninstall and reinstall of iohook did the trick, as long as I have my package.json configured properly. You'd see console output during the iohook install indicating that the install process is automatically downloading and extracting the needed binaries.

have tried reinstall many times, not resolved this problem.
my confuse is: the error msg said : 'Uncaught Error: Cannot find module '/Users/dev/Desktop/code/xxx/out/builds/electron-v75-darwin-x64/build/Release/iohook.node'  but there is no 'builds/' directory in '/Users/dev/Desktop/code/xxx/out/' after I installed iohook...

**Comment by a-keramat** [comment]
`/Users/dev/Desktop/code/xxx/out/builds/electron-v75-darwin-x64/build/Release/iohook.node`

xxx/out is that all ? 
shouldn't it be like `Project_Name\`**node_modules\iohook**`\builds\electron-v80-darwin-x64`  ?

**Comment by quanweibai** [comment]
> node_modules

set 'iohook' as  externals configuration option in webpack fixed this problem.

thanks.

**Comment by quanweibai** [comment]
> `/Users/dev/Desktop/code/xxx/out/builds/electron-v75-darwin-x64/build/Release/iohook.node`
> 
> xxx/out is that all ?
> shouldn't it be like `Project_Name\`**node_modules\iohook**`\builds\electron-v80-darwin-x64` ?

set 'iohook' as externals configuration option in webpack fixed this problem.

thanks.

**Comment by Djiit** [comment]
I'm closing this ticket as it appears to be resolved. Free free to ping me here if needed.
